### ISSUE TITLE
Firefox can't be called issue

### ISSUE THREAD

**Issue by manan2501** [OWASP/QRLJacking#37]
QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Desktop/QRLJacking/QRLJacker/core/browser.py", line 107, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Desktop/QRLJacking/QRLJacker/core/browser.py", line 120, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Desktop/QRLJacking/QRLJacker/core/browser.py", line 135, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by manan2501** [comment]
QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[ ! ] Couldn't open FireFox! Check installation intrsuctions again!


I HAVE INSTALLED THIS TOOLS FOR 7 TIMES AS PER THE INSTRUCTIONS. I DONT KNOW WHAT TO DO NEXT.                          :(                  :(

**Comment by D4Vinci** [comment]
You are missing the geckodriver or didn't update firefox to the latest version!
That's the reason behind the error.
Read the instructions again!

**Comment by manan2501** [comment]
I have installed geckodriver (4 times) and my firefox version is 60.4.0. Should it work on that version?

**Comment by AlainChaaya** [comment]
i have the same problem :(

**Comment by manan2501** [comment]
> i have the same problem :(

this is what I replied to your issue xD

**Comment by AlainChaaya** [comment]
> > i have the same problem :(
> 
> this is what I replied to your issue xD

hahahahahha yeah i remembered you while commenting it

**Comment by D4Vinci** [comment]
> I have installed geckodriver (4 times) and my firefox version is 60.4.0. Should it work on that version?

If you installed it 4 times wrong, it wouldn't matter 😄 See this tutorial I just published:
https://www.youtube.com/watch?v=sYtH5-K2JZc
I used the latest version of Firefox in this video which is 66 so update your Firefox 😉

**Comment by AlainChaaya** [comment]
Can you just tell us how did you update your firefox?? I mean i am doing so but it doesn’t seem updating idk its very weird sorry and thanks

**Comment by D4Vinci** [comment]
I think googling it would be better lol 😄

**Comment by AlainChaaya** [comment]
> QrlJacker Module(grabber/whatsapp) > run
> [+] Using the default useragent
> [ ! ] Couldn't open FireFox! Check installation intrsuctions again!
> 
> I HAVE INSTALLED THIS TOOLS FOR 7 TIMES AS PER THE INSTRUCTIONS. I DONT KNOW WHAT TO DO NEXT. :( :(

Hey manan I followed this link to be able to install/upgrade correctly the latest version of firefox (the one required for the QRLJacking) https://www.tecmint.com/install-firefox-quantum-in-linux/

**Comment by AlainChaaya** [comment]
Man the issue is still here... I installed firefox quantum and it's version 66.0.3 but I still get this error, I don't understand why.
It seems like the code can't see the new firefox or something like that, I don't really know.
If that's the case, is there any code line that I should replace?

**Comment by AlainChaaya** [comment]
i ran the command: firefox --version to check and suprisingly it's showed this:
root@kali:~# firefox --version
Mozilla Firefox 60.4.0

**Comment by D4Vinci** [comment]
> i ran the command: firefox --version to check and suprisingly it's showed this:
> root@kali:~# firefox --version
> Mozilla Firefox 60.4.0

Then no need to say you updated it wrong 😄 try uninstalling all the versions you are having and install version 66 only again.

**Comment by AlainChaaya** [comment]
I’ve searched a lot and couldn’t find the right way to update this firefox since the auto update of firefox keeps it at version 60
Do you have any solution in mind? Or any reference that u know?

**Comment by AlainChaaya** [comment]
I have uninstalled Firefox and then reinstalled it.
I kept it on the home directory and I'm launching it using the command ./firefox or double clicking in this specific folder.
As you can see here the version is 66 as required:
root@kali:~/firefox/firefox# ./firefox --version
Mozilla Firefox 66.0.3

But even with that I still get the same error when running:

<Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 107, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 135, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 120, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

**Comment by D4Vinci** [comment]
Just released a new version try it and give me the new output!

**Comment by AlainChaaya** [comment]
Just tried it and got this:

<Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > Exception in thread QR updater thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by AlainChaaya** [comment]
When i run again directly after this error I still get this error:

QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[!] Couldn't open Firefox! Check the installation instructions again!

**Comment by D4Vinci** [comment]
try typing `report` while debug mode is activated

**Comment by AlainChaaya** [comment]
Done, that's what i got from it:

QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
 Exception: Message: 'geckodriver' executable may have wrong permissions. 

 Trackback: 
Exception -> name 'traceback' is not defined
    Input -> run
Trackback -> 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 61, in new_session
    new_headless[module_name]["Controller"] = Firefox(profile)#options=self.opts) # Inserting the browser object
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable may have wrong permissions. 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/QRLJacking/QRLJacker/core/module.py", line 55, in handle
    handler(args)
  File "/root/QRLJacking/QRLJacker/core/module.py", line 137, in command_run
    Settings.headless_browser.new_session(exec_info.name, exec_info.url, global_options["useragent"][2])
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 68, in new_session
    traceback.print_exc()
NameError: name 'traceback' is not defined
[!] run is not recognized as an internal command !
[+] Maybe you meant : , runreload, refresh, resource
[+] Type help or ? to learn more..

**Comment by D4Vinci** [comment]
well then try running the framework as root

**Comment by AlainChaaya** [comment]
Still the same (was actually already on root but double checked and tried again)

**Comment by 40R40L** [comment]
Hi guys, I had the same issue and I found the solution.

The problem is that when i installed QrlJacker with root permissions and I tried to run it as root something went wrong with Firefox.

I tried to show Firefox version on a terminal as root and i had this message:
```
root@Silver: ~/Desktop# Firefox version
Running Firefox as root in a regular user's session is not supported. ($HOME is /home/user which is owned by user.)
```

When I installed QrlJacker again, but this time with a normal user permission (same as Firefox) it works!!!

I hope this could help you :)

**Comment by D4Vinci** [comment]
> Hi guys, I had the same issue and I found the solution.
> 
> The problem is that when I installed QrlJacker with root permissions and I tried to run it as root something went wrong with Firefox. ( same error as @manan2501)
> 
> I tried to show Firefox version on a terminal as root and I had this message:
> 
> ```
> root@Silver: ~/Desktop# Firefox version
> Running Firefox as root in a regular user's session is not supported. ($HOME is /home/user which is owned by user.)
> ```
> When I installed QrlJacker again, but this time with normal user permission (same as Firefox) it works!!!
> 
> I hope this could help you :)

Makes sense, try it guys, of course, this would the cause of the problem as geckodriver can't call Firefox

**Comment by D4Vinci** [comment]
Closed the issue because the error reason revealed and appeared it's not from the framework. Reopen if the problem persists.
Thanks, @40R40L 😄

**Comment by AlainChaaya** [comment]
what if I only have a root user and not a normal user using root
permissions?

**Comment by AlainChaaya** [comment]
And the firefox --version was giving an answer since if i was in its
directory

**Comment by jepunband** [comment]
have geckodriver and the latest firefox 66. but still receive errors..

Exception in thread QR updater thread:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/jeret/Tools/QRLJacking/QRLJacker/core/browser.py", line 116, in website_qr
controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

QrlJacker Module(grabber/whatsapp) > Exception in thread Idle detector thread:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/jeret/Tools/QRLJacking/QRLJacker/core/browser.py", line 132, in check_img
controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'

Exception in thread Webserver manager thread:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/jeret/Tools/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by Cardi8080** [comment]
> Hi guys, I had the same issue and I found the solution.
> 
> The problem is that when i installed QrlJacker with root permissions and I tried to run it as root something went wrong with Firefox. ( same error as @manan2501)
> 
> I tried to show Firefox version on a terminal as root and i had this message:
> 
> ```
> root@Silver: ~/Desktop# Firefox version
> Running Firefox as root in a regular user's session is not supported. ($HOME is /home/user which is owned by user.)
> ```
> 
> When I installed QrlJacker again, but this time with a normal user permission (same as Firefox) it works!!!
> 
> I hope this could help you :)

Can you specify how you installed it with not root pernissions? Thankyou in advance

**Comment by 40R40L** [comment]
> > Hi guys, I had the same issue and I found the solution.
> > The problem is that when i installed QrlJacker with root permissions and I tried to run it as root something went wrong with Firefox. ( same error as @manan2501)
> > I tried to show Firefox version on a terminal as root and i had this message:
> > ```
> > root@Silver: ~/Desktop# Firefox version
> > Running Firefox as root in a regular user's session is not supported. ($HOME is /home/user which is owned by user.)
> > ```
> > 
> > 
> > When I installed QrlJacker again, but this time with a normal user permission (same as Firefox) it works!!!
> > I hope this could help you :)
> 
> Can you specify how you installed it with not root pernissions? Thankyou in advance

Hi ,

try to create a user different thant root and install the app using that user

**Comment by azamet90** [comment]
i have the same problem

**Comment by kingabhijit01** [comment]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by whitehat101010** [comment]
I start by saying that despite having done everything as written, I also found the problem despite the fact that in the other kali Linux that I have on another stick (2019.4) nothing of the sort has ever happened to me and I can't understand why now  Yes !  now I have kali Linux 2020.1be after downloading qrljacking done all the steps as in my previous kali Linux, when I am in the program, selected port 1337 and left host on 0.0.0.0, I open nhrok in another terminal with the command  "Ngrok http 1337" then returning from the qrljaking program and writing "run" and press enter what I hoped does not happen but only this: 


QrlJacker Module (grabber / whatsapp)> run
 [+] Using the default useragent
 [+] Running a thread to keep the QR image [whatsapp]
 [+] Waiting for sessions on whatsapp
 [+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp].
 [+] Initializing webserver ... [whatsapp]

 QrlJacker Module (grabber / whatsapp)> Exception in thread QR updater thread:
 Traceback (most recent call last):
 File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
 self.run ()
 File "/usr/lib/python3.6/threading.py", line 864, in run
 self._target (* self._args, ** self._kwargs)
 File "/root/Desktop/QRLJacking/QRLJacker/core/browser.py", line 107, in website_qr
 controller = self.browsers [module_name] ["Controller"]
 KeyError: 'whatsapp'

 Exception in thread Idle detector thread:
 Traceback (most recent call last):
 File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
 self.run ()
 File "/usr/lib/python3.6/threading.py", line 864, in run
 self._target (* self._args, ** self._kwargs)
 File "/root/Desktop/QRLJacking/QRLJacker/core/browser.py", line 120, in check_img
 controller = self.browsers [module_name] ["Controller"]
 KeyError: 'whatsapp'

 Exception in thread Webserver manager thread:
 Traceback (most recent call last):
 File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
 self.run ()
 File "/usr/lib/python3.6/threading.py", line 864, in run
 self._target (* self._args, ** self._kwargs)
 File "/root/Desktop/QRLJacking/QRLJacker/core/browser.py", line 135, in serve_module
 self.browsers [module_name] ["host"] = "http: //" + host
 KeyError: 'whatsapp'.




then if I write "CTRL + C" and rewrite "run" and hit enter it tells me this !

QrlJacker Module (grabber / whatsapp)> run
 [+] Using the default useragent
 [!  ] Couldn't open FireFox!  Check installation intrsuctions again!😓



if someone recently encountered my same problem and would help me I would be very grateful !!!!! 🙏🏼

**Comment by RUGMJ7443** [comment]
I'm having the same issue I've tried running as root with sudo and without root still, get the same error has anyone found a fix?

**Comment by karthikiller** [comment]
Still it's not working

**Comment by H4xl0r** [comment]
No fix till jet ? 
what a mess , not working anymore

**Comment by stylishstar002** [comment]
> Exception in thread Webserver manager thread:
> Traceback (most recent call last):
> File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
> self.run()
> File "/usr/lib/python3.7/threading.py", line 870, in run
> self._target(*self._args, **self._kwargs)
> File "/root/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
> self.browsers[module_name]["host"] = "http://"+host
> KeyError: 'whatsapp'

I also have this same problem

**Comment by shelby-67** [comment]
I have same problem can anyone help me step by step?

**Comment by nasyx-rakeeb** [comment]
did anyone find the solution

**Comment by shelby-67** [comment]
What i send ?

احصل على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: Nasyx Rakeeb ***@***.***>
‏‏تم الإرسال: Tuesday, June 7, 2022 3:03:07 PM
إلى: OWASP/QRLJacking ***@***.***>
نسخة: shelby-67 ***@***.***>; Comment ***@***.***>
‏‏الموضوع: Re: [OWASP/QRLJacking] (KeyError: 'whatsapp') Firefox can't be called issue (#37)


did anyone find the solution

**Comment by nasyx-rakeeb** [comment]
@shelby-67 what are u trying to say? i Dont get it

**Comment by shelby-67** [comment]
Oh about error

احصل على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: SHELBHY 67 ***@***.***>
‏‏تم الإرسال: Tuesday, June 7, 2022 3:04:35 PM
إلى: OWASP/QRLJacking ***@***.***>; OWASP/QRLJacking ***@***.***>
نسخة: Comment ***@***.***>
‏‏الموضوع: Re: [OWASP/QRLJacking] (KeyError: 'whatsapp') Firefox can't be called issue (#37)

What i send ?

احصل على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: Nasyx Rakeeb ***@***.***>
‏‏تم الإرسال: Tuesday, June 7, 2022 3:03:07 PM
إلى: OWASP/QRLJacking ***@***.***>
نسخة: shelby-67 ***@***.***>; Comment ***@***.***>
‏‏الموضوع: Re: [OWASP/QRLJacking] (KeyError: 'whatsapp') Firefox can't be called issue (#37)


did anyone find the solution

**Comment by fffff515** [comment]
> Модуль QrlJacker (граббер/whatsapp) > запустить [+] Использование юзерагента по умолчанию [ ! ] Не удалось открыть FireFox! Проверьте инструкции по установке еще раз!
> 
> Я УСТАНАВЛИВАЛ ЭТОТ ИНСТРУМЕНТ 7 РАЗ СОГЛАСНО ИНСТРУКЦИИ. Я НЕ ЗНАЮ, ЧТО ДЕЛАТЬ ДАЛЬШЕ. :( :(

Translated by Google Translate
Please tell me what processor you have. I had the same problem, as it turned out the problem with geckodriver

**Comment by immortal-007** [comment]
> firefox

i am using python 3.10  
and 91.8 firefox       still error accure 

QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
Exception in thread QR updater thread:
[+] Waiting for sessions on whatsapp
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
Exception in thread Idle detector thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
[+] Initializing webserver... [whatsapp]
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run

QrlJacker Module(grabber/whatsapp) > Exception in thread Webserver manager thread:
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/immortal/Downloads/QRLJacking/QRLJacker/core/browser.py", line 133, in website_qr
Traceback (most recent call last):
    controller = self.browsers[module_name]["Controller"]
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
KeyError: 'whatsapp'
    self._target(*self._args, **self._kwargs)
  File "/home/immortal/Downloads/QRLJacking/QRLJacker/core/browser.py", line 149, in check_img
    controller = self.browsers[module_name]["Controller"]
KeyError: 'whatsapp'
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/immortal/Downloads/QRLJacking/QRLJacker/core/browser.py", line 167, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'


I hope it can be solve  advance thankyou

**Comment by Mergim-dev** [comment]
what

**Comment by Mergim-dev** [comment]
<Module(grabber/whatsapp) > run
[+] Using the default useragent
[!] Couldn't open Firefox! Check the installation instructions again!
